### ISSUE TITLE
绘制一个虚线圆圈

### ISSUE THREAD

**Issue by SevenChan07** [SevenChan07/pensieve#25]
```html
<circle r="5" class="cir" />
```

```css
.cir {
  fill: none
  stroke-dasharray: 2.0
}
```
