### ISSUE TITLE
在Safari浏览器中，字体会自动变细

### ISSUE THREAD

**Issue by SevenChan07** [SevenChan07/pensieve#36]
<https://stackoverflow.com/questions/21278020/font-weight-turns-lighter-on-mac-safari>

```css
body {
  -webkit-font-smoothing: subpixel-antialiased;
}
```
